run:
  tests: true
  timeout: 30s
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  fast: true
  enable:
    - gocyclo
    - govet
    - misspell
    - nestif
    - revive
    - staticcheck
    - unused

severity:
  default-severity: warning
  case-sensitive: false

linters-settings:
  gocyclo:
    min-complexity: 20
  funlen:
    lines: 100
    statements: 80
  gocritic:
    disabled-checks:
      - exitAfterDefer
  gosec:
    severity: medium
    config:
      G301: "0755" # Maximum allowed permissions mode for os.Mkdir and os.MkdirAll - Default: "0750"
      G302: "0644" # Maximum allowed permissions mode for os.OpenFile and os.Chmod - Default: "0600"
      G306: "0644" # Maximum allowed permissions mode for os.WriteFile and ioutil.WriteFile - Default: "0600"
  misspell:
    locale: US
  nestif:
    min-complexity: 4

output:
  print-issued-lines: false
  sort-results: true
  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.
  show-stats: true