run:
  tests: true
  timeout: 30s
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  fast: true
  enable:
    # - cyclop
    # - gocyclo
    - govet
    # - maintidx
    - misspell
    - unused
    ##- unparam
    #- errcheck
    #- funlen
    #- gocritic
    - gocyclo
    #- goimports
    #- gosec
    #- gosimple
    #- ineffassign
    - nestif
    - staticcheck
    #- revive
    #- staticcheck
    #- typecheck
    #- unused

severity:
  default-severity: warning
  case-sensitive: false

linters-settings:
  gocyclo:
    min-complexity: 35

  funlen:
    lines: 100
    statements: 80

  gocritic:
    disabled-checks:
      - exitAfterDefer

  gosec:
    severity: medium
    config:
      G301: "0755" # Maximum allowed permissions mode for os.Mkdir and os.MkdirAll - Default: "0750"
      G302: "0644" # Maximum allowed permissions mode for os.OpenFile and os.Chmod - Default: "0600"
      G306: "0644" # Maximum allowed permissions mode for os.WriteFile and ioutil.WriteFile - Default: "0600"

  maintidx:
    under: 150

  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 30
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 0.0
    # Should ignore tests.
    # Default: false
    skip-tests: true

  misspell:
    locale: US

  nestif:
    min-complexity: 4  # Minimal complexity of if statements to report. - Default: 5
