run:
  tests: true
  timeout: 30s
  modules-download-mode: readonly
  allow-parallel-runners: true

severity:
  default-severity: warning
  case-sensitive: false

linters:
  disable-all: true
  fast: true
  enable:
    - funlen
    - gocyclo
    - govet
    - misspell
    - nestif
    - revive
    - staticcheck
    - unused

linters-settings:
  funlen:
    lines: 150
    statements: 105
  gocyclo:
    min-complexity: 20
  misspell:
    locale: US
  nestif:
    min-complexity: 4

output:
  print-issued-lines: false
  sort-results: true
  sort-order:
    - linter
    - severity
    - file # filepath, line, and column.
  show-stats: true