coverage:
  precision: 2
  range: "65...85"
  status:
    project:
      default:
        target: auto
        threshold: 30%
        informational: true
    patch:
      default:
        informational: true

github_checks:
  annotations: true