name: lint-code
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
  pull_request_target:
    types: [opened, edited, reopened, ready_for_review]

env:
  GO_VERSION: "~1.21"
  GO111MODULE: "on"

jobs:
  run-golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=5m --out-format=github-actions
          skip-save-cache: false
